app/__init__.py
from flask import Flask

from routes import router
from config import mongo


def create_app():
    app = Flask(__name__)
    app.config['MONGO_URI'] = 'mongodb+srv://admin:6iKyAiPFT9JAabB8@cluster0.9ck3e.mongodb.net/mydb?retryWrites=true' \
                              '&w=majority'

    mongo.init_app(app)

    app.config['SECRET_KEY'] = 'tubaroesVoadores'
    app.register_blueprint(router)
    app.run()


if __name__ == "__main__":
    create_app()

app/routes.py
from flask import Blueprint, redirect, render_template, request, url_for, flash, Flask
from sympy.core.logic import Not
from config import mongo
from calc import calcMax

router = Blueprint("router", __name__)



@router.route("/", methods=["GET"])
def main():
    medicine_collection = mongo.db.medicine

    items = medicine_collection.find()
    items = [item for item in items]

    return render_template("main.html", items=items, lenght=len(items))


@router.route("/add_medicine", methods=["POST"])
def add_medicine():
    medicine_collection = mongo.db.medicine
    
    name = request.form.get("Nome").capitalize()
    description = request.form.get("Descricao")
    price = request.form.get("Preco")

    price = int(price)
    count = calcMax(price)
    max = count * price

    if medicine_collection.find_one({"name": name}) == None:
        item = {"name": name, "price": price, "description": description, "count": count, "max": max}
        medicine_collection.insert_one(item)

    else:
        flash('Remédio já cadastrado!')

    return redirect(url_for("router.main"))

app/templates/main.html
<!DOCTYPE html>
<html>
<title>Farmax</title>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1"/>
<link
        rel="stylesheet"
        href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"
        crossorigin="anonymous"
>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500&display=swap" rel="stylesheet">

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"></script>
<style>
    *{
       font-family: 'Poppins', sans-serif;
    };
    .jumbotron {
      background-color: #f4511e;
      color: #fff;
      padding: 100px 25px;
    }
    .container-fluid {
      padding: 60px 50px;
    }
    .main {
      background-color: #f6f6f6;
      padding: 0 16rem;
    }
    .logo {
      width: 200px;
    }
    @media screen and (max-width: 768px) {
      .col-sm-4 {
        text-align: center;
      }
    }
    .alert-error {
      margin-bottom: 15px;
      padding: 8px;
      background-color: white;
      color: red;
      border-radius: 5px;
      width: 100%;
      text-align: center;
    }

    img {
      width: 100%; /* Set width to 100% */
      margin: auto;
    }

</style>
<body class="main">

<div class="jumbotron jumbotron-fluid  bg-primary text-white">
  <div class="container">
    <h3 class="display-4">FARMAX</h3>
  </div>
</div>
<!-- Container image -->

<div class="container-fluid bg-grey">
    <div class="row">
        <div class="col-sm-8">
            <h2>Sobre nosso projeto</h2>
            <p>Calculamos o lucro máximo do seu remédio em um mês, considerando o
                rendimento de vendas da nossa empresa! Para calcular o lucro máximo basta que você</p>
            <ul>
                <li>Coloque o nome do seu remédio</li>
                <li>Escolha um preço</li>
                <li>Espere seu lucro</li>
            </ul>
        </div>
    </div>
</div>
<!-- Container image -->

<!-- Forms -->
<div class="container-fluid">
    <div class="row ">
        <div class="col-sm-6 align-items-center">
          <div class="card" style="width: 70%;">
            <div class="card-body">
              <h5 class="card-title">Adicionar remédio</h5>
               <form action="{{ url_for('router.add_medicine') }}" method="post">
                        <div class="form-group">
                            <label for="Nome">Nome</label>
                            <input
                                    type="text"
                                    class="form-control"
                                    id="Nome"
                                    name="Nome"
                                    style="width: 100%; "
                                    placeholder="Nome do remédio"
                                    required="true"
                            />
                        </div>
                        <div class="form-group">
                            <label for="Descricao">Descrição</label>
                            <textarea
                                    class="form-control"
                                    rows="5"
                                    style="width: 100%; resize: vertical;"
                                    id="Descricao"
                                    name="Descricao"
                            ></textarea>
                        </div>
                        <div class="form-group">
                            <label for="Preco">Preço</label>
                            <input
                                    type="number"
                                    style="width: 100%;"
                                    class="form-control"
                                    id="Preco"
                                    name="Preco"
                                    placeholder="Preço do remédio"
                                    required="true"
                            />
                        </div>
                        <div styles="width:100%; align-items: center;">
                            <button
                                    type="submit"
                                    style="width: 100%;"
                                    class="btn btn-primary"
                            >
                                Calcular
                            </button>
                            <p>
                              {% for message in get_flashed_messages() %}
                                <div class="alert-error">{{ message }}</div>
                              {% endfor %}
                            </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-sm-6">
            <h3 class="list-group-item list-group-item-light"> Lista de remédios</h3>
            <ul class="list-group" style="max-height: 412px; overflow: auto;">
                {% if lenght > 0 %}
                {% for item in items %}
                <li class="list-group-item">
                    <p class="float-left">{{item.name}}</p>
                    <button type="button" class="btn btn-primary float-right" data-toggle="modal"
                            data-target="#{{item.name}}">
                        sobre
                    </button>
                </li>
                {% endfor %}
                {% else %}
                {% endif %}
            </ul>
        </div>
    </div>
</div>

{% for item in items %}
<div class="modal fade" id="{{item.name}}" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Informação sobre o remédio</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div>
                    <h6>Lucro máximo</h6>
                    <ul>
                        <li><p>Venda <strong>{{item.count}}</strong> unidades para obter o lucro maximo</p></li>
                        <li><p>Lucro maximo: <strong>R$ {{item.max}}</strong> </p></li>
                    </ul>
                    <h6>Informações Gerais</h6>
                    <ul>
                        <li><p>Nome: {{item.name}}</p></li>
                        <li><p>Preço: R$ {{item.price}}</p></li>
                    </ul>
                </div>
                {% if item.description%}
                    <div>
                        <h6>Descrição:</h6>
                        <p style="text-align: justify;">{{item.description}}</p>
                    </div>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endfor %}
</body>
</html>